version: '3.4'

services:
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: test_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: changeme
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: {}
